device_tracker:
  - platform: mqtt
    devices:
      fingerprint: 'home/presence/fingerprint'
	 
automation:	 
- alias: 'Boolean Fingerprint William toggle'
  initial_state: True
  trigger:
    - platform: state
      entity_id: device_tracker.fingerprint
      to: 'Fingerprint_William_detected'
      from: 'unknown'
  action:
    - service: input_boolean.toggle
      entity_id: input_boolean.presence_william
    - service: mqtt.publish
      data_template:
        topic: 'home/presence/fingerprint'
        payload: 'unknown'